### PR TITLE
Enable and update link for Google Satellite

### PR DESCRIPTION
**Pull request by tahajahangir**

### CODE REVIEW

**Comment by mjk912** [comment]
Thanks. Fixed!

**Comment by tahajahangir** [comment]
@mjk912 The pull request is closed without merge, How you did fix it?

**Comment by tahajahangir** [comment]
@mjk912 The pull request is closed without merge, How you did fix it?

**Comment by mjk912** [comment]
manually without updating. 
have other changes too. 
doing it all together tomorrow. 

sorry for troubles

**Pull request closed without merging**
